flake-update:
- changed-files:
    - any-glob-to-any-file: 'flake.*'

vic-dots:
- changed-files:
    - any-glob-to-any-file: 'modules/home/vic/dots/**/*'

victorias-secret:
- changed-files:
    - any-glob-to-any-file: 'modules/home/vic/secrets/**/*'
