imports = ["./nixos/leader.nix"]

[devshell]
packages = ["sops", "age"]

[[commands]]
package = "nixfmt-rfc-style"

[[commands]]
package = "nh"

[[commands]]
name = "nh-reboot"
command = "nix fmt && nh os boot && reboot"
help = "Nix Format / OS Boot"

[[commands]]
name = "nh-clean-boot"
command = "nix fmt && nh os boot && nh clean all && nh os boot"
help = "Clear boot"

[[commands]]
name = "nr-switch"
command = "sudo nixos-rebuild --flake . switch"
help = "nixos-rebuild switch"

[[commands]]
name = "dw-switch"
command = "sudo darwin-rebuild --flake . switch"
help = "nixos-rebuild switch"


[[commands]]
name = "vic-sops"
help = "Sops for vic"
command = """
if test -z "${1:-}"; then
  sops --config ./modules/home/vic/sops.yaml edit ./modules/home/vic/secrets.yaml
else
  sops --config ./modules/home/vic/sops.yaml "${@}"
fi
"""