imports = ["./nix.toml", "./nixos/leader.nix"]

[devshell]
packages = ["sops", "age", "ssh-to-age"]

[[commands]]
package = "nh"

[[commands]]
name = "nh-reboot"
command = "nix fmt && nh os boot && reboot"
help = "Nix Format / OS Boot"

[[commands]]
name = "nh-clean-boot"
command = "nix fmt && nh os boot && nh clean all && nh os boot"
help = "Clear boot"

[[commands]]
name = "nr-switch"
command = "sudo nixos-rebuild --flake . switch"
help = "nixos-rebuild switch"


[[commands]]
name = "vic-sops-edit"
help = "Edit secrets for vic"
command = """
sops --config ./modules/home/vic/sops.yaml edit ./modules/home/vic/${1:-secrets.yaml}
"""