imports = ["./nixos/leader.nix"]

[devshell]
packages = ["sops", "age", "nh"]

[[commands]]
name = "vic-sops"
help = "Sops for vic"
command = """
if test -z "${1:-}"; then
  sops --config ./modules/home/vic/sops.yaml edit ./modules/home/vic/secrets.yaml
else
  sops --config ./modules/home/vic/sops.yaml "${@}"
fi
"""

[[commands]]
name = "logs-home-manager-vic"
help = "See logs for home-manager-vic activation"
command = """
journalctl -u home-manager-vic.service "${@}"
"""

[[commands]]
name = "os-rebuild"
help = "OS rebuild"
command = """
nix run .#os-rebuild "${@}"
""""

[[commands]]
name = "clean"
help = "nh clean all"
command = "nh clean all"

[[commands]]
name = "fmt"
help = "nix fmt"
command = "nix fmt"
