name: build-systems
on:
  pull_request:
  push:
    branches: [main]

jobs:
  find-systems:
    name: find-systems
    runs-on: ubuntu-latest
    outputs:
      nixos: ${{ steps.finder.outputs.nixos }}
      darwin: ${{ steps.finder.outputs.darwin }}
      dintel: ${{ steps.finder.outputs.dintel }}
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
      - id: finder
        run: |
          nixos=$(nix eval --accept-flake-config --quiet .#.lib.hostsBySystem --apply 'f: f "x86_64-linux"' --json)
          darwin=$(nix eval --accept-flake-config --quiet .#.lib.hostsBySystem --apply 'f: f "aarch64-darwin"' --json)
          dintel=$(nix eval --accept-flake-config --quiet .#.lib.hostsBySystem --apply 'f: f "x86_64-darwin"' --json)

          echo "nixos=$nixos"
          echo "darwin=$darwin"
          echo "dintel=$dintel"

          echo "nixos=$nixos" >> $GITHUB_OUTPUT
          echo "darwin=$darwin" >> $GITHUB_OUTPUT
          echo "dintel=$dintel" >> $GITHUB_OUTPUT

  x86_64-linux:
    name: ${{ matrix.host }} x86_64-linux
    needs: [find-systems]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ${{ fromJSON(needs.find-systems.outputs.nixos) }}
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --accept-flake-config --no-link --print-out-paths .#.nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

  aarch64-linux:
    name: ${{ matrix.host }} aarch64-darwin
    needs: [find-systems]
    runs-on: macos-latest
    strategy:
      matrix:
        host: ${{ fromJSON(needs.find-systems.outputs.darwin) }}
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --accept-flake-config  --no-link --print-out-paths .#.darwinConfigurations.${{ matrix.host }}.system

  x86_64-darwin:
    name: ${{ matrix.host }} x86_64-darwin
    needs: [find-systems]
    runs-on: macos-13
    strategy:
      matrix:
        host: ${{ fromJSON(needs.find-systems.outputs.dintel) }}
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --accept-flake-config --no-link --print-out-paths .#.darwinConfigurations.${{ matrix.host }}.system


