name: flake-check-no-build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  flake-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # macos macos-latest is broken?
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix store gc
      - run: nix flake check --no-build # dont build systems/derivations just check their types.
      - run: nix store gc
