name: "flake update"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * MON,WED,FRI,SUN'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Make changes to pull request
        run: nix flake update 2>&1 | tee .nix-flake-update.out
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          assignees: vic
          reviewers: vic
          commit-message: nix flake update
          branch: flake-updates
          delete-branch: true
          title: 'flake-update'
          body-path: '.nix-flake-update.out'
