name: "flake update"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * MON,WED,FRI,SUN'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git checkout -b "flake-update-$(date '+%F')"
          title="Updating flake inputs $(date)"
          (
            echo "$title"
            echo -ne "\n\n\n\n"
            echo '```shell'
            echo '$ nix flake update'
            nix flake update --accept-flake-config 2>&1
            echo '```'
            echo -ne "\n\n\n\n"
            echo 'request-checks: true'
          ) | tee /tmp/commit-message.md
          changes="$(git status -s | grep -o 'M ' | wc -l)"
          if test "$changes" -eq 0; then
            echo "No changes"
            exit 0
          fi
          git status -s | grep 'M ' | cut -d 'M' -f 2 | xargs git add
          git commit --author "Victor Borja <vic@apache.org>" -F /tmp/commit-message.md --no-signoff --no-verify
          gh pr create --base main --label flake-update --reviewer vic --assignee vic --body-file /tmp/commit-message.md --title "$title" | tee /tmp/pr-url
          echo gh pr merge --delete-branch --rebase --auto "$(< /tmp/pr-url)"

