name: "labeler"
on:
  pull_request_target:
    types: [assigned, opened, reopened, edited, ready_for_review, synchronize]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5

