on:
  label:
  pull_request:
  push:
    branches: [main]

jobs:
  flake-check:
    if: contains(github.event.pull_request.labels.*.name, 'flake-update')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check

  nix-fmt:
    name: nix-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#checks.x86_64-linux.formatted
