on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix-fmt:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix build .#checks.x86_64-linux.formatted
