name: upterm
on:
  workflow_dispatch:
jobs:
  upterm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: upterm
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH=$HOME/.nix-profile/bin:$PATH
          env NIXPKGS_ALLOW_UNFREE=1 nix profile install nixpkgs#vscode --impure
          nix profile install nixpkgs#upterm nixpkgs#tmux nixpkgs#vim
          ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
          ssh-keygen -q -t ed25519 -N "" -f ~/.ssh/id_ed25519
          echo -e "Host *\nStrictHostKeyChecking no\nCheckHostIP no\nTCPKeepAlive yes\nServerAliveInterval 30\nServerAliveCountMax 180\nVerifyHostKeyDNS yes\nUpdateHostKeys yes\n" >> $HOME/.ssh/config
          ssh-keyscan uptermd.upterm.dev 2> /dev/null >> ~/.ssh/known_hosts
          cat <(cat ~/.ssh/known_hosts | awk '{ print "@cert-authority * " $2 " " $3 }') >> ~/.ssh/known_hosts
          mkdir -p $HOME/.upterm
          tmux new -d -s upterm "upterm host --accept --github-user vic | tee $HOME/.upterm/out.log"
          while ! grep 'SSH Session:' $HOME/.upterm/out.log; do sleep 1 ; done
          echo Waiting
          while ! grep 'Client joined' $HOME/.upterm/upterm.log >/dev/null; do sleep 10; done
          echo Joined
          while ! grep 'Client left' $HOME/.upterm/upterm.log >/dev/null; do sleep 10; done
          echo Left
