name: upterm
on:
  workflow_dispatch:
jobs:
  upterm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: upterm
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/known_hosts
          echo "StrictHostKeyChecking no" >> $HOME/.ssh/config
          nix profile install nixpkgs#upterm nixpkgs#openssh nixpkgs#tmux nixpkgs#vim
          export PATH=$HOME/.nix-profile/bin:$PATH
          upterm -- host --github-user vic --force-command 'tmux attach -t gh' -- tmux new -t gh
