name: upterm-macos-latest
on:
  workflow_dispatch:
jobs:
  upterm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: upterm
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.config/nixpkgs
          echo '{ allowUnfree = true; }' > ~/.config/nixpkgs/config.nix
          nix develop --accept-flake-config --impure .#upterm --command gh-action
