name: upterm
on:
  workflow_dispatch:
jobs:
  upterm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: nix flake update
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run:
          nix run nixpkgs#upterm -- host --github-user vic --force-command 'tmux attach -t gh' -- tmux new -t gh
