name: upterm
on:
  workflow_dispatch:
jobs:
  upterm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: owenthereal/action-upterm@v1
        with:
           limit-access-to-users: vic
           wait-timeout-minutes: 5
